# Uncomment the next line to define a global platform for your project
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'UTDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UTDemo

  target 'UTDemoTests' do
    inherit! :search_paths
    pod 'OCMock'
    pod 'Specta'
    pod 'Expecta'
    pod 'OHHTTPStubs'
    # Pods for testing
  end

  target 'UTDemoUITests' do
    pod 'OCMock'
    pod 'Specta'
    pod 'Expecta'
    pod 'OHHTTPStubs'
    # Pods for testing
  end

end
